# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DARK_CALIB_PATH: /tmp
  SLACK_ICON: 🎉
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        version: latest
        project_id: ${{ env.DS_GCLOUD_PROJECT_ID }}
        service_account_email: ${{ env.DS_SERVICE_ACCOUNT_EMAIL }}
        service_account_key: ${{ secrets.DS_GITHUB_CI_CD_SA_KEY }}
        export_default_credentials: true

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install in dev mode
      run: |
        python setup.py develop
    - name: Test with pytest
      run: |
        python setup.py test
    - name: Prepare build latex reports
      run: |
         sudo apt-get update
         sudo apt-get install -y texlive-latex-recommended texlive-publishers texlive-bibtex-extra texlive-science
    - name: Build latex reports
      run: |
        python setup.py gen_report
    - name: Set failure state
      if: failure()
      run: |
        echo "::set-env name=SLACK_ICON::🔴"

    - name: Publish pdf reports
      uses: actions/upload-artifact@v2
      with:
        path: reports/latex/*/*.pdf


    # Create your own channel
    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: '${{ env.SLACK_ICON }} Testing'
        mention: 'here'
        mention_if: always()
        channel: '#template_ds' #repo_name_to_be_changed
        url: https://hooks.slack.com/services/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
        commit: true
        token: ${{ secrets.GITHUB_TOKEN }}


